### ISSUE TITLE
MBP 14 M1 Pro fails to sleep when Battery Toolkit is active

### ISSUE THREAD

**Issue by mrdc** [mhaeuser/Battery-Toolkit#27] opened 2024-07-12 17:36 UTC
Hello,

My MBP 14 M1 Pro (Sonoma 14.5) fails to sleep when I use `Battery Toolkit 1.4` (https://github.com/mhaeuser/Battery-Toolkit/releases/tag/1.4).
When I close the lid, MBP stays awake: when I take my AirPods Pro they immediately connect to my MBP, which wasn't happening before Battery Toolkit. This is also confirmed by running `pmset`:
`pmset -g log | grep -e " Sleep " -e " DarkWake " -e " Wake "`

In logs it's clearly visible that MBP is constantly awakening. I've cancelled all wake up timers before sleep to minimize disturbing Apple processes, but still it's not sleeping.

**Comment by mhaeuser** [comment] 2024-07-12 17:38
Sleep is disabled while charging by design and cannot be circumvented. Does it work as expected once the device is charged?

**Comment by mhaeuser** [comment] 2024-07-15 20:05
Sorry, but you need to explicitly specify whether the laptop is charging or not when describing the behavior, preferably also whether charging finished before or after closing the lid. As-is, this information is not very useful.

**Closed as completed** 2024-07-24 18:57 UTC

**Comment by mhaeuser** [comment] 2024-07-24 18:59
@mrdc Would you mind elaborating what you tweaked?
